In [1]:
import numpy as np 
import time

In [6]:
lista = []
for i in range(10):
    lista.append([i,i*2])
print(lista)

[[0, 0], [1, 2], [2, 4], [3, 6], [4, 8], [5, 10], [6, 12], [7, 14], [8, 16], [9, 18]]


In [10]:
for element in lista:
    print(element[1])

0
2
4
6
8
10
12
14
16
18


In [5]:
for child in lista:
    print(child)

1
3
4
5
6
7
8
9
10


In [2]:
print("helloword")

helloword


In [11]:
x = [1, 3, 4, 5, 6, 7, 8, 9, 10]
x.append(11)

[1, 3, 4, 5, 6, 7, 8, 9, 10, 11]


In [22]:
print(f"Oi Leo bjs{x[0]} {x[1]} {x[2]}")

Oi Leo bjs1 3 4


In [31]:
s=input()

In [35]:
print(s)

12 13 14 15


In [37]:
v = s.split(" ")
print(v)
print(type(v))

['12', '13', '14', '15']
<class 'list'>


In [41]:
u=[]
print("Dentro do for")
for element in v:
    print(element)
    u.append(int(element))
print("-"*10)
print(element)
print(u)
print(type(u))
print(u[0])
print(type(u[0]))

Dentro do for
12
13
14
15
----------
15
[12, 13, 14, 15]
<class 'list'>
12
<class 'int'>


In [30]:
s_int = float(s)
print(type(s_int))
print(s_int)

<class 'float'>
12.0


In [45]:
print(range(50,100))
print(type(range(50,100)))

range(50, 100)
<class 'range'>


In [48]:
for i in range(10):
    if i%2==0:
        print(i)
    elif i%3==0:
        print(i*10)
    else:
        print(i*100)

0
100
2
30
4
500
6
700
8
90


In [59]:
def soma(a,b):
    return a+b

In [60]:
def mul(a,b):
    return a*b

In [61]:
def div(a,b):
    return a/b

In [68]:
dict = {
    "A": mul,
    "B": soma,
    "C": div
    }

In [71]:
print(dict["C"](2,2))

1.0


In [72]:
P=print

In [73]:
P("Hello World!")

Hello World!


In [78]:
x,y,z=0,1,2

In [79]:
x,y=y,x

In [80]:
print(x)
print(y)
print(z)

1
0
2


In [82]:
x=0
while(x<10):
    print(x)
    x+=1

0
1
2
3
4
5
6
7
8
9


In [94]:
a = True
b = False
c = 124134314123
d = 0

In [98]:
if (not c or a) and (not d):
    print("A")

A


In [90]:
print(type(c))

<class 'int'>


In [99]:
np.log2(4)

2.0

In [133]:
A = np.array([[0,1,2,3],
              [3,4,5,6],
              [8,9,0,1]])

In [135]:
print(A)

[[0 1 2 3]
 [3 4 5 6]
 [8 9 0 1]]


In [136]:
print(np.shape(A))

(3, 4)


In [132]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [130]:
print(A)

[[0 1 2 3]]


In [109]:
x = "abcdefghi"

In [126]:
a = x.index("d")
x = x[:a]+"BLA"+x[a:]

In [127]:
print(x)

jklabcBLAdBLAefghijkljkl
